// Contenu du site : destinations, expériences et voyage signature.
// Pour ajouter une destination, copiez un objet et adaptez les champs.
// `scene` choisit l'illustration : ocean, mountain, savanna, ice, desert, coast, city.
// `sky` donne les deux couleurs du ciel (haut, bas) de l'illustration.

window.SOLSTICE_DATA = {
  destinations: [
    {
      id: "maldives",
      name: "Atoll de Baa",
      country: "Maldives",
      region: "Asie",
      coords: "5°15′N · 73°05′E",
      season: "Nov. – avr.",
      flight: "10 h 30",
      nights: 7,
      price: 8900,
      scene: "ocean",
      sky: ["#1B6F86", "#F2C48D"],
      stay: "Villa sur pilotis avec piscine, majordome dédié",
      text: "Réserve de biosphère de l'UNESCO. Plongée avec les raies manta à Hanifaru Bay, dîner privé sur un banc de sable à marée basse.",
    },
    {
      id: "kyoto",
      name: "Kyoto",
      country: "Japon",
      region: "Asie",
      coords: "35°00′N · 135°46′E",
      season: "Mars – avr. · Nov.",
      flight: "14 h",
      nights: 9,
      price: 7400,
      scene: "city",
      sky: ["#3A3355", "#E8A48F"],
      stay: "Ryokan centenaire avec onsen privatif",
      text: "Visite des jardins de Katsura sur invitation, dîner kaiseki préparé par un chef triplement étoilé, soirée à Gion avec une geiko.",
    },
    {
      id: "patagonie",
      name: "Torres del Paine",
      country: "Chili",
      region: "Amériques",
      coords: "50°56′S · 72°59′W",
      season: "Nov. – mars",
      flight: "16 h",
      nights: 8,
      price: 9800,
      scene: "mountain",
      sky: ["#27465E", "#C9D6DC"],
      stay: "Lodge d'architecte face aux Cuernos",
      text: "Randonnées guidées vers la base des tours, chevauchée avec des gauchos, navigation jusqu'au front du glacier Grey.",
    },
    {
      id: "serengeti",
      name: "Serengeti",
      country: "Tanzanie",
      region: "Afrique",
      coords: "2°20′S · 34°50′E",
      season: "Juin – oct.",
      flight: "10 h",
      nights: 6,
      price: 11200,
      scene: "savanna",
      sky: ["#8A4B2A", "#F0B45E"],
      stay: "Camp de toile mobile qui suit la Grande Migration",
      text: "Traversée de la rivière Mara aux premières loges, safaris avec un pisteur maasaï, vol en montgolfière à l'aube.",
    },
    {
      id: "bora-bora",
      name: "Bora Bora",
      country: "Polynésie française",
      region: "Océanie",
      coords: "16°30′S · 151°44′W",
      season: "Mai – oct.",
      flight: "22 h",
      nights: 10,
      price: 12500,
      scene: "ocean",
      sky: ["#0F5C73", "#9FD9D2"],
      stay: "Bungalow sur le lagon, vue sur le mont Otemanu",
      text: "Pique-nique sur un motu privé, nage avec les raies léopards, croisière au coucher du soleil en pirogue à balancier.",
    },
    {
      id: "laponie",
      name: "Saariselkä",
      country: "Laponie finlandaise",
      region: "Europe",
      coords: "68°25′N · 27°25′E",
      season: "Déc. – mars",
      flight: "4 h 30",
      nights: 5,
      price: 5900,
      scene: "ice",
      sky: ["#0B1A33", "#1F5D63"],
      stay: "Igloo de verre chauffé sous le ciel arctique",
      text: "Chasse aux aurores boréales avec un photographe, traîneau de huskies dans la forêt boréale, sauna sur un lac gelé.",
    },
    {
      id: "alula",
      name: "AlUla",
      country: "Arabie saoudite",
      region: "Moyen-Orient",
      coords: "26°37′N · 37°55′E",
      season: "Oct. – mars",
      flight: "6 h",
      nights: 5,
      price: 6800,
      scene: "desert",
      sky: ["#5A2F3A", "#E9A06B"],
      stay: "Resort troglodyte creusé dans les canyons de grès",
      text: "Visite privée des tombeaux nabatéens d'Hégra, dîner sous les étoiles dans la vallée d'Ashar, survol en hélicoptère.",
    },
    {
      id: "amalfi",
      name: "Côte amalfitaine",
      country: "Italie",
      region: "Europe",
      coords: "40°38′N · 14°36′E",
      season: "Mai – sept.",
      flight: "2 h",
      nights: 6,
      price: 4900,
      scene: "coast",
      sky: ["#2C6C9A", "#F5CFA0"],
      stay: "Palazzo du XVIIe siècle à flanc de falaise",
      text: "Riva en bois privé jusqu'à Capri, cours de cuisine dans un jardin de citronniers, concert dans les jardins de la Villa Rufolo.",
    },
    {
      id: "rajasthan",
      name: "Udaipur",
      country: "Inde",
      region: "Asie",
      coords: "24°35′N · 73°41′E",
      season: "Oct. – mars",
      flight: "9 h",
      nights: 8,
      price: 6500,
      scene: "desert",
      sky: ["#6B2E4F", "#F2B27A"],
      stay: "Palais de marbre blanc au milieu du lac Pichola",
      text: "Dîner royal sur une barge illuminée, visite des ateliers de miniatures, nuit en camp de luxe dans le désert du Thar.",
    },
  ],

  experiences: [
    {
      title: "Dîner à cinq mètres sous la mer",
      place: "Maldives",
      duration: "3 heures",
      price: 1400,
      text: "Menu en six services dans un restaurant sous-marin, raies et requins de récif derrière la paroi de verre.",
    },
    {
      title: "Montgolfière sur la Grande Migration",
      place: "Tanzanie",
      duration: "Aube, 4 heures",
      price: 850,
      text: "Décollage à 6 h, survol des troupeaux de gnous, petit-déjeuner au champagne servi dans la savane.",
    },
    {
      title: "Nuit sous les aurores boréales",
      place: "Laponie",
      duration: "1 nuit",
      price: 1200,
      text: "Igloo de verre, réveil programmé à l'apparition des aurores, guide photographe à disposition.",
    },
    {
      title: "Cérémonie du thé avec un maître",
      place: "Kyoto",
      duration: "2 heures",
      price: 680,
      text: "Pavillon de thé privatisé dans un temple zen, préparation du matcha selon l'école Urasenke.",
    },
    {
      title: "Hélicoptère jusqu'au champ de glace",
      place: "Patagonie",
      duration: "Demi-journée",
      price: 2300,
      text: "Atterrissage sur le Campo de Hielo Sur, verre de whisky servi avec de la glace millénaire.",
    },
    {
      title: "Goélette privée en mer Tyrrhénienne",
      place: "Italie",
      duration: "1 journée",
      price: 3900,
      text: "Équipage de quatre, baignade dans les criques des Faraglioni, déjeuner de fruits de mer à bord.",
    },
  ],

  signature: {
    title: "Le tour du monde en jet privé",
    days: 24,
    guests: "12 voyageurs",
    price: 148000,
    departure: "Départ le 9 janvier 2027 de Paris-Le Bourget",
    stops: [
      { days: "J1 – J3", place: "Kyoto", note: "Ryokan, kaiseki, jardins impériaux" },
      { days: "J4 – J7", place: "Bora Bora", note: "Bungalow sur le lagon, motu privé" },
      { days: "J8 – J11", place: "Patagonie", note: "Lodge, glacier Grey, hélicoptère" },
      { days: "J12 – J15", place: "Serengeti", note: "Camp mobile, montgolfière" },
      { days: "J16 – J19", place: "Maldives", note: "Villa sur pilotis, dîner sous-marin" },
      { days: "J20 – J24", place: "AlUla", note: "Hégra, dîner étoilé, retour à Paris" },
    ],
  },

  testimonials: [
    {
      quote: "Le camp avait été déplacé la veille pour suivre les troupeaux. Nous avons vu la traversée de la Mara depuis le petit-déjeuner.",
      who: "Claire et Mathieu",
      trip: "Serengeti, août 2026",
    },
    {
      quote: "Chaque transfert était déjà réglé à notre arrivée. Nous n'avons sorti notre passeport qu'une fois.",
      who: "Famille Okafor",
      trip: "Tour du monde, janvier 2026",
    },
    {
      quote: "Les aurores sont apparues à 2 h du matin, le guide nous a réveillés comme promis. Inoubliable.",
      who: "Sofia R.",
      trip: "Laponie, février 2026",
    },
  ],
};
