// Tout le contenu du site Bluehour.
// months : 12 valeurs de janvier à décembre. 2 = période idéale, 1 = bonne période, 0 = déconseillé.
// collections : identifiants de la liste `collections` ci-dessous.

window.BLUEHOUR_DATA = {
  collections: [
    {
      id: "skylines",
      name: "Skylines & penthouses",
      short: "Skylines",
      image: "images/dubai.jpg",
      text: "Piscines à débordement au 70e étage, bains face à Manhattan, rooftops privatisés. La ville vue d'en haut.",
    },
    {
      id: "iles",
      name: "Îles & lagons",
      short: "Îles",
      image: "images/maldives.jpg",
      text: "Sable blanc, eaux turquoise et villas sur pilotis. Les archipels les plus préservés de l'océan Indien et du Pacifique.",
    },
    {
      id: "riviera",
      name: "Riviera & beach clubs",
      short: "Riviera",
      image: "images/monaco.jpg",
      text: "Terrasses sur la Méditerranée, beach clubs d'Ibiza, villas privées de Marbella. L'art de vivre au bord de l'eau.",
    },
    {
      id: "nature",
      name: "Nature spectaculaire",
      short: "Nature",
      image: "images/kauai.jpg",
      text: "Falaises de la Na Pali Coast, jungle de Bali, granit des Seychelles. Des paysages qui imposent le silence.",
    },
  ],

  destinations: [
    {
      id: "dubai",
      name: "Dubaï",
      country: "Émirats arabes unis",
      region: "Moyen-Orient",
      collections: ["skylines"],
      image: "images/dubai.jpg",
      coords: "25°11′N · 55°16′E",
      tagline: "La ville qui touche le ciel",
      intro: "Une piscine à débordement qui semble se jeter dans la skyline, le Burj Khalifa illuminé à l'heure bleue, puis le désert à quarante minutes. Dubaï se vit en hauteur et en contrastes.",
      highlights: [
        "Penthouse avec piscine privée face au Burj Khalifa",
        "Dîner dans les dunes de Al Marmoom, servi sous un ciel sans lumière",
        "Accès privé à la plateforme At the Top Sky, au 148e étage",
      ],
      stay: "Penthouse de Downtown avec piscine à débordement et majordome",
      months: [2, 2, 2, 1, 0, 0, 0, 0, 0, 1, 2, 2],
      flight: "6 h 45",
      timezone: "+2 h",
      nights: 5,
      price: 5400,
      itinerary: [
        { day: "Jour 1", title: "Arrivée en suite", text: "Accueil au pied de l'avion, transfert en Rolls-Royce, cocktail sur la terrasse de votre penthouse." },
        { day: "Jour 2", title: "Downtown à l'heure bleue", text: "Dubai Mall en visite privée, puis At the Top Sky au coucher du soleil." },
        { day: "Jour 3", title: "Le désert", text: "Réserve de Al Marmoom en 4x4, fauconnerie, dîner sous les étoiles." },
        { day: "Jours 4 et 5", title: "Mer et spa", text: "Yacht privé autour de Palm Jumeirah, hammam et soins signature." },
      ],
    },
    {
      id: "new-york",
      name: "New York",
      country: "États-Unis",
      region: "Amérique du Nord",
      collections: ["skylines"],
      image: "images/new-york.jpg",
      coords: "40°45′N · 73°59′W",
      tagline: "Manhattan depuis votre baignoire",
      intro: "Un bain de marbre noir suspendu au-dessus de Midtown, l'Empire State Building en face et One World Trade Center qui s'allume au coucher du soleil. New York vue d'où personne ne la voit.",
      highlights: [
        "Suite d'angle au 80e étage sur Billionaires' Row",
        "Visite privée du MoMA avant l'ouverture au public",
        "Survol de Manhattan en hélicoptère, portes ouvertes",
      ],
      stay: "Suite panoramique avec salle de bain vitrée face à Manhattan",
      months: [0, 0, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1],
      flight: "8 h",
      timezone: "−6 h",
      nights: 5,
      price: 6900,
      itinerary: [
        { day: "Jour 1", title: "Midtown", text: "Transfert depuis JFK en hélicoptère, dîner au comptoir d'un chef étoilé." },
        { day: "Jour 2", title: "Art et galeries", text: "MoMA avant l'ouverture, galeries de Chelsea avec une curatrice." },
        { day: "Jour 3", title: "Vue du ciel", text: "Vol portes ouvertes au-dessus de Manhattan, soirée jazz à Harlem." },
        { day: "Jours 4 et 5", title: "À votre rythme", text: "Personal shopper sur Madison Avenue, brunch à Tribeca, spectacle à Broadway." },
      ],
    },
    {
      id: "chicago",
      name: "Chicago",
      country: "États-Unis",
      region: "Amérique du Nord",
      collections: ["skylines"],
      image: "images/chicago.jpg",
      coords: "41°53′N · 87°37′W",
      tagline: "Un rooftop au-dessus du lac Michigan",
      intro: "La berge du lac Michigan s'illumine comme un collier, la skyline de l'architecture moderne se reflète dans votre piscine en mosaïque. Chicago est la ville des architectes, et vous la regardez depuis son sommet.",
      highlights: [
        "Penthouse avec piscine en mosaïque et terrasse de 300 m²",
        "Croisière architecturale privée sur la Chicago River",
        "Soirée blues dans un club du South Side avec un musicien",
      ],
      stay: "Penthouse sur la Gold Coast avec piscine privée sur le toit",
      months: [0, 0, 0, 1, 1, 2, 2, 2, 2, 1, 0, 0],
      flight: "9 h",
      timezone: "−7 h",
      nights: 4,
      price: 5900,
      itinerary: [
        { day: "Jour 1", title: "Gold Coast", text: "Installation au penthouse, apéritif sur le toit face au lac." },
        { day: "Jour 2", title: "Architecture", text: "Croisière privée sur la rivière, Frank Lloyd Wright à Oak Park." },
        { day: "Jour 3", title: "Art Institute", text: "Visite privée de l'Art Institute, dîner chez un chef triplement étoilé." },
        { day: "Jour 4", title: "Le lac", text: "Voilier privé sur le lac Michigan, soirée blues." },
      ],
    },
    {
      id: "monaco",
      name: "Monaco & Riviera",
      country: "Monaco et France",
      region: "Europe",
      collections: ["riviera"],
      image: "images/monaco.jpg",
      coords: "43°44′N · 7°25′E",
      tagline: "La Riviera au crépuscule",
      intro: "Depuis votre terrasse, la côte s'allume de Monaco jusqu'à l'Italie. Sofas bas, bougies, lavande en pot et la Méditerranée qui passe du rose au bleu nuit. La Riviera à son heure la plus belle.",
      highlights: [
        "Villa sur les hauteurs de Roquebrune avec vue sur la baie",
        "Riva privé jusqu'à Saint-Jean-Cap-Ferrat pour le déjeuner",
        "Places en tribune pour le Grand Prix de Monaco, fin mai",
      ],
      stay: "Villa contemporaine avec terrasse panoramique sur la baie de Monaco",
      months: [0, 0, 1, 1, 2, 2, 1, 1, 2, 1, 0, 0],
      flight: "1 h 30",
      timezone: "Même heure",
      nights: 4,
      price: 4800,
      itinerary: [
        { day: "Jour 1", title: "Arrivée par la mer", text: "Hélicoptère de Nice à Monaco en sept minutes, dîner sur la terrasse." },
        { day: "Jour 2", title: "Cap-Ferrat", text: "Riva privé, déjeuner les pieds dans l'eau, Villa Ephrussi de Rothschild." },
        { day: "Jour 3", title: "Villages perchés", text: "Èze et Saint-Paul-de-Vence avec un guide, parfumeur à Grasse." },
        { day: "Jour 4", title: "Monte-Carlo", text: "Musée océanographique, soirée au casino." },
      ],
    },
    {
      id: "maldives",
      name: "Maldives",
      country: "Maldives",
      region: "Océan Indien",
      collections: ["iles"],
      image: "images/maldives.jpg",
      gallery: "images/maldives-breakfast.jpg",
      coords: "4°10′N · 73°30′E",
      tagline: "L'heure bleue sur le lagon",
      intro: "Villas en chaume au bord d'un sable presque blanc, lagon translucide et petit-déjeuner servi sur le ponton face au large. Aux Maldives, la seule décision de la journée est l'heure de la baignade.",
      highlights: [
        "Villa sur la plage avec piscine privée et accès direct au lagon",
        "Petit-déjeuner servi sur le ponton, face à l'océan",
        "Plongée avec les raies manta à Hanifaru Bay, de juin à novembre",
      ],
      stay: "Villa de plage sous toit de chaume, piscine privée, majordome",
      months: [2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2],
      flight: "10 h 30",
      timezone: "+3 h",
      nights: 7,
      price: 9800,
      itinerary: [
        { day: "Jour 1", title: "Hydravion", text: "Accueil à Malé, 45 minutes d'hydravion au-dessus des atolls." },
        { day: "Jours 2 et 3", title: "Le lagon", text: "Snorkeling avec un biologiste marin, dîner sur un banc de sable." },
        { day: "Jours 4 et 5", title: "Sous l'eau", text: "Plongée avec les raies manta, spa sur pilotis." },
        { day: "Jours 6 et 7", title: "Rien", text: "Petit-déjeuner flottant, croisière au coucher du soleil avec les dauphins." },
      ],
    },
    {
      id: "seychelles",
      name: "Seychelles",
      country: "Seychelles",
      region: "Océan Indien",
      collections: ["iles", "nature"],
      image: "images/seychelles.jpg",
      coords: "4°40′S · 55°28′E",
      tagline: "Des marches jusqu'à l'océan",
      intro: "Un escalier de bois descend vers une terrasse, un cocotier penché, et en bas un océan d'un bleu que les photos n'exagèrent pas. Les Seychelles, c'est aussi la forêt primaire et les tortues géantes.",
      highlights: [
        "Villa à flanc de colline sur Mahé avec terrasse sur la mer",
        "Excursion en catamaran vers La Digue et l'Anse Source d'Argent",
        "Vallée de Mai à Praslin, forêt classée à l'UNESCO",
      ],
      stay: "Villa sur la colline, terrasse en teck et escalier privé vers la crique",
      months: [1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 1],
      flight: "10 h",
      timezone: "+2 h",
      nights: 8,
      price: 8400,
      itinerary: [
        { day: "Jours 1 à 3", title: "Mahé", text: "Villa sur la colline, marché de Victoria, randonnée du Morne Seychellois." },
        { day: "Jours 4 et 5", title: "Praslin", text: "Vallée de Mai et ses cocos de mer, plage d'Anse Lazio." },
        { day: "Jour 6", title: "La Digue", text: "Vélo jusqu'à l'Anse Source d'Argent, déjeuner créole." },
        { day: "Jours 7 et 8", title: "Île privée", text: "Nuit sur une île privée avec les tortues géantes d'Aldabra." },
      ],
    },
    {
      id: "bali",
      name: "Bali",
      country: "Indonésie",
      region: "Asie",
      collections: ["nature", "iles"],
      image: "images/bali.jpg",
      coords: "8°30′S · 115°15′E",
      tagline: "Une piscine au-dessus de la jungle",
      intro: "À Ubud, les piscines à débordement épousent la courbe de la vallée et les rizières descendent vers la rivière Ayung. Au réveil, la jungle, les temples et les offrandes du matin.",
      highlights: [
        "Villa avec piscine à débordement sur la vallée de l'Ayung",
        "Cérémonie de purification à Tirta Empul avec un prêtre",
        "Lever de soleil au sommet du mont Batur",
      ],
      stay: "Villa suspendue au-dessus de la jungle d'Ubud, piscine privée",
      months: [0, 0, 0, 1, 2, 2, 2, 2, 2, 1, 0, 0],
      flight: "16 h",
      timezone: "+6 h",
      nights: 8,
      price: 6800,
      itinerary: [
        { day: "Jours 1 à 3", title: "Ubud", text: "Villa sur la vallée, rizières de Tegallalang, cours de cuisine balinaise." },
        { day: "Jour 4", title: "Spiritualité", text: "Purification à Tirta Empul, bénédiction par un prêtre." },
        { day: "Jour 5", title: "Le volcan", text: "Ascension du mont Batur pour le lever du soleil." },
        { day: "Jours 6 à 8", title: "Uluwatu", text: "Villa sur la falaise, danse Kecak au temple, surf." },
      ],
    },
    {
      id: "kauai",
      name: "Kauai",
      country: "Hawaï, États-Unis",
      region: "Pacifique",
      collections: ["nature", "iles"],
      image: "images/kauai.jpg",
      coords: "22°10′N · 159°38′W",
      tagline: "La Na Pali Coast depuis votre bureau",
      intro: "Des falaises vertes de mille mètres qui plongent dans une eau turquoise, et votre fauteuil en rotin face à elles. Kauai est l'île la plus sauvage de l'archipel, accessible par la mer, les airs ou à pied.",
      highlights: [
        "Maison d'architecte vitrée sur la côte nord",
        "Survol de la Na Pali Coast et du canyon de Waimea en hélicoptère",
        "Catamaran le long des falaises, avec les dauphins à long bec",
      ],
      stay: "Maison vitrée sur la côte nord, vue sur les falaises",
      months: [1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1],
      flight: "20 h",
      timezone: "−12 h",
      nights: 7,
      price: 11500,
      itinerary: [
        { day: "Jours 1 et 2", title: "Hanalei", text: "Installation sur la côte nord, baie d'Hanalei en paddle." },
        { day: "Jour 3", title: "Vue du ciel", text: "Hélicoptère au-dessus de la Na Pali Coast et de Waimea." },
        { day: "Jours 4 et 5", title: "Par la mer", text: "Catamaran le long des falaises, snorkeling aux Tunnels." },
        { day: "Jours 6 et 7", title: "À pied", text: "Sentier Kalalau avec un guide, luau privé." },
      ],
    },
    {
      id: "ibiza",
      name: "Ibiza",
      country: "Espagne",
      region: "Europe",
      collections: ["riviera"],
      image: "images/ibiza.jpg",
      coords: "38°54′N · 1°25′E",
      tagline: "Beach clubs et criques secrètes",
      intro: "Un hôtel sur la plage, des cabanas blanches autour d'une piscine turquoise, la tour de guet d'Es Cavallet au bout de la baie. Ibiza a aussi un visage calme : ses criques du nord et ses fincas dans les pins.",
      highlights: [
        "Suite en surplomb de la plage avec cabana réservée",
        "Yacht privé jusqu'à Formentera pour la journée",
        "Coucher du soleil face à Es Vedrà, depuis une finca privée",
      ],
      stay: "Suite en front de mer avec terrasse et cabana privée",
      months: [0, 0, 0, 0, 1, 2, 2, 2, 2, 1, 0, 0],
      flight: "2 h",
      timezone: "Même heure",
      nights: 5,
      price: 4200,
      itinerary: [
        { day: "Jour 1", title: "Playa d'en Bossa", text: "Installation face à la mer, dîner les pieds dans le sable." },
        { day: "Jour 2", title: "Formentera", text: "Yacht privé, baignade à Ses Illetes, déjeuner de langouste." },
        { day: "Jour 3", title: "Dalt Vila", text: "Vieille ville classée à l'UNESCO, marché de Las Dalias." },
        { day: "Jours 4 et 5", title: "Le nord", text: "Criques de Benirràs, coucher de soleil face à Es Vedrà." },
      ],
    },
    {
      id: "marbella",
      name: "Marbella",
      country: "Espagne",
      region: "Europe",
      collections: ["riviera"],
      image: "images/marbella.jpg",
      coords: "36°30′N · 4°53′W",
      tagline: "Cinéma sous les étoiles, piscine illuminée",
      intro: "Une villa privée sur la Golden Mile, un écran géant au bord de la piscine, des sofas qui descendent jusqu'à l'eau. Idéale pour se retrouver entre amis ou en famille, avec un chef et une équipe dédiés.",
      highlights: [
        "Villa privée de 8 chambres avec cinéma extérieur et piscine chauffée",
        "Chef privé et service de maison pendant tout le séjour",
        "Journée à Ronda et dans les bodegas d'Andalousie",
      ],
      stay: "Villa privée de 8 chambres, cinéma extérieur, chef et majordome",
      months: [0, 0, 0, 1, 2, 2, 1, 1, 2, 1, 0, 0],
      flight: "2 h 30",
      timezone: "Même heure",
      nights: 7,
      price: 7900,
      itinerary: [
        { day: "Jour 1", title: "La villa", text: "Accueil par votre majordome, dîner du chef au bord de la piscine." },
        { day: "Jour 2", title: "Puerto Banús", text: "Yacht privé vers Gibraltar, déjeuner à bord." },
        { day: "Jour 3", title: "Ronda", text: "Pont de Ronda, dégustation dans une bodega, retour par les villages blancs." },
        { day: "Jours 4 à 7", title: "Vie de villa", text: "Golf, spa à domicile, séances de cinéma sous les étoiles." },
      ],
    },
    {
      id: "miami",
      name: "Miami",
      country: "Floride, États-Unis",
      region: "Amérique du Nord",
      collections: ["riviera", "skylines"],
      image: "images/miami.jpg",
      coords: "25°47′N · 80°08′W",
      tagline: "Transats dans l'eau, palmiers et Art déco",
      intro: "Des transats posés dans quelques centimètres d'eau turquoise, des arches de cascade blanches, des palmiers partout. Miami mélange l'Art déco de South Beach, l'art contemporain de Wynwood et le calme de Key Biscayne.",
      highlights: [
        "Villa avec piscine lagon et transats immergés",
        "Art Basel Miami Beach en décembre, avec accès VIP",
        "Journée en bateau jusqu'aux Keys",
      ],
      stay: "Villa tropicale avec piscine lagon et cascades",
      months: [2, 2, 2, 2, 1, 0, 0, 0, 0, 0, 1, 2],
      flight: "10 h",
      timezone: "−6 h",
      nights: 5,
      price: 6200,
      itinerary: [
        { day: "Jour 1", title: "South Beach", text: "Villa sur l'eau, dîner à Ocean Drive." },
        { day: "Jour 2", title: "Wynwood", text: "Street art et galeries avec un collectionneur, Design District." },
        { day: "Jour 3", title: "Les Keys", text: "Bateau privé jusqu'à Islamorada, déjeuner de homard." },
        { day: "Jours 4 et 5", title: "Everglades", text: "Hydroglisseur dans les Everglades, soirée à Little Havana." },
      ],
    },
    {
      id: "cancun",
      name: "Cancún & Riviera Maya",
      country: "Mexique",
      region: "Caraïbes & Mexique",
      collections: ["iles"],
      image: "images/cancun.jpg",
      coords: "21°08′N · 86°44′W",
      tagline: "Un balcon sur la mer des Caraïbes",
      intro: "Du balcon, la plage blanche file à perte de vue et la mer passe du turquoise au bleu profond. Au sud, la Riviera Maya cache des cenotes, des sites mayas et des villages de pêcheurs.",
      highlights: [
        "Suite en étage élevé avec balcon vitré sur la mer",
        "Baignade dans un cenote privé, fermé au public",
        "Chichén Itzá au lever du soleil, avant l'arrivée des visiteurs",
      ],
      stay: "Suite d'angle avec balcon panoramique sur la mer des Caraïbes",
      months: [2, 2, 2, 2, 1, 0, 0, 0, 0, 0, 1, 2],
      flight: "11 h",
      timezone: "−7 h",
      nights: 7,
      price: 5600,
      itinerary: [
        { day: "Jours 1 et 2", title: "Cancún", text: "Suite face à la mer, catamaran jusqu'à Isla Mujeres." },
        { day: "Jour 3", title: "Chichén Itzá", text: "Arrivée au lever du soleil avec un archéologue." },
        { day: "Jours 4 et 5", title: "Cenotes", text: "Cenote privé, Tulum et ses ruines au-dessus de la mer." },
        { day: "Jours 6 et 7", title: "Holbox", text: "Île sans voitures, requins-baleines de juin à septembre." },
      ],
    },
  ],

  experiences: [
    {
      id: "bain-manhattan",
      title: "Un bain au-dessus de Manhattan",
      place: "New York",
      dest: "new-york",
      image: "images/new-york.jpg",
      duration: "Soirée",
      price: 1900,
      text: "Baignoire de marbre noir remplie au moment exact du coucher du soleil, champagne millésimé et vue sur One World Trade Center.",
    },
    {
      id: "petit-dejeuner-ponton",
      title: "Petit-déjeuner sur le ponton",
      place: "Maldives",
      dest: "maldives",
      image: "images/maldives-breakfast.jpg",
      duration: "Matinée",
      price: 450,
      text: "Fruits tropicaux, viennoiseries du chef et jus pressés, servis sur un ponton en bois, sous un parasol, face au large.",
    },
    {
      id: "cinema-etoiles",
      title: "Cinéma privé sous les étoiles",
      place: "Marbella",
      dest: "marbella",
      image: "images/marbella.jpg",
      duration: "Soirée",
      price: 1200,
      text: "Écran géant au bord de la piscine illuminée, film choisi à l'avance, dîner du chef servi sur les sofas.",
    },
    {
      id: "na-pali-helico",
      title: "Survol de la Na Pali Coast",
      place: "Kauai",
      dest: "kauai",
      image: "images/kauai.jpg",
      duration: "2 heures",
      price: 2400,
      text: "Hélicoptère privé le long des falaises, au-dessus du canyon de Waimea et des cascades du mont Waialeale.",
    },
    {
      id: "rooftop-chicago",
      title: "Rooftop privatisé à l'heure bleue",
      place: "Chicago",
      dest: "chicago",
      image: "images/chicago.jpg",
      duration: "Soirée",
      price: 3200,
      text: "La piscine et la terrasse rien que pour vous, un mixologue et un pianiste, et la ville qui s'allume au bord du lac.",
    },
    {
      id: "jungle-ubud",
      title: "Journée dans la jungle d'Ubud",
      place: "Bali",
      dest: "bali",
      image: "images/bali.jpg",
      duration: "Journée",
      price: 680,
      text: "Balade dans les rizières avec un agriculteur, bénédiction au temple, puis après-midi à la piscine au-dessus de la vallée.",
    },
  ],

  grandTour: {
    title: "Skylines & lagons",
    subtitle: "De Dubaï aux Seychelles, 16 nuits",
    image: "images/seychelles.jpg",
    price: 21900,
    nights: 16,
    departures: ["8 janvier 2027", "5 février 2027", "12 mars 2027"],
    text: "Trois escales dans l'océan Indien, reliées en jet privé. On commence par la ville la plus verticale du monde, on finit sur une île où l'on se déplace à vélo.",
    stops: [
      { dest: "dubai", nights: 3, note: "Penthouse, désert d'Al Marmoom, yacht autour de Palm Jumeirah" },
      { dest: "maldives", nights: 7, note: "Villa de plage, hydravion, raies manta et banc de sable" },
      { dest: "seychelles", nights: 6, note: "Villa sur la colline, La Digue, tortues géantes" },
    ],
    included: [
      "Vols en jet privé entre les trois escales",
      "Vols Paris aller et retour en classe affaires",
      "Hébergements en villa ou suite, pension complète",
      "Toutes les expériences privatisées du programme",
      "Un conseiller Bluehour joignable 24 h/24",
    ],
  },

  testimonials: [
    {
      quote: "On nous avait promis le coucher du soleil depuis la baignoire. Il y avait aussi un orage au loin sur le New Jersey. Personne n'avait pu le prévoir, et c'était parfait.",
      who: "Hélène et Marc",
      trip: "New York, octobre 2025",
    },
    {
      quote: "Notre conseillère avait séjourné dans la villa elle-même. Elle savait quelle chambre avait la meilleure vue sur la vallée.",
      who: "Famille Lemaire",
      trip: "Bali, juillet 2026",
    },
    {
      quote: "Trois pays, deux hydravions, un jet, et nous n'avons jamais attendu nos bagages.",
      who: "Karim A.",
      trip: "Skylines & lagons, février 2026",
    },
  ],

  months: ["Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"],
};
